from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
from gmusicapi import Mobileclient
import logging
import os

GMUSIC_LOGIN = os.environ.get('LOGIN')
TELEGRAM_TOKEN = os.environ.get('TOKEN')
PLAYLIST_NAME = 'autogenerated'

def get_playlist(api):
    user_playlists = [playlist for playlist in api.get_all_playlists() if playlist['name'] == PLAYLIST_NAME]
    if len(user_playlists) == 0:
        print('Create new playlist')
        return api.create_playlist('autogenerated')
    else:
        return user_playlists[0]['id']

def start(update, context):
    context.bot.send_message(chat_id=update.effective_chat.id, text="I'm a bot, please talk to me!")
    
def echo(update, context):
    api = Mobileclient()
    api.oauth_login(GMUSIC_LOGIN)
    search_results = api.search(update.message.text)
    song_results = search_results['song_hits'][0]['track']
    api.add_songs_to_playlist(get_playlist(api), song_results['storeId'])
    context.bot.send_message(chat_id=update.effective_chat.id, text=song_results['title'])

logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                     level=logging.INFO)


updater = Updater(token=TELEGRAM_TOKEN, use_context=True)
dispatcher = updater.dispatcher

start_handler = CommandHandler('start', start)
dispatcher.add_handler(start_handler)

echo_handler = MessageHandler(Filters.text, echo)
dispatcher.add_handler(echo_handler)

updater.start_polling()
