import logging
from gmusicapi import Mobileclient
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
from main import add_to_playlist, USER_WHITELIST
from app_secrets import GMUSIC_LOGIN, TELEGRAM_TOKEN


START_MESSAGE = 'Hey! Please send the name of a song and the artist.'
PLAYLIST_NAME = 'autogenerated'

def main():

    logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                        level=logging.INFO)

    api = Mobileclient()

    # If executing the script for the first time, run this command to generate a
    # credentials file. On linux systems, the file can often be found under
    # ~/.local/share/gmusicapi/
    # api.perform_oauth()

    api.oauth_login(GMUSIC_LOGIN)


    def start(update, context):
        context.bot.send_message(chat_id=update.effective_chat.id, text=START_MESSAGE)


    def echo(update, context):
        result = add_to_playlist(api, update.message.text)
        context.bot.send_message(chat_id=update.effective_chat.id, text=result)


    updater = Updater(token=TELEGRAM_TOKEN, use_context=True)
    dispatcher = updater.dispatcher

    start_handler = CommandHandler('start', start, Filters.user(username=USER_WHITELIST))
    dispatcher.add_handler(start_handler)

    echo_handler = MessageHandler(Filters.user(username=USER_WHITELIST), echo)
    dispatcher.add_handler(echo_handler)

    updater.start_polling()

if __name__ == "__main__":
    main()
